### ISSUE TITLE
Chapter 4 exercise different from vocareum

### ISSUE THREAD

**Issue by bgschiller** [LaunchCodeEducation/thinkcspy#13]
(This was copied from a student's post on Piazza)

I don't know if other people will have this issue...but I took the instructions from the book and worked the graded ch. 4 problem in there.  Then copied/pasted into Vocareum.  It seems the Vocareum instructions are a bit more descriptive than the book.  Maybe the book can be updated to avoid confusion for others?

Book:
b. Write a loop that prints each number and its square on a new line.
I thought it was asking for something that looked like this:
10
100
12
144, etc.
Vocareum:
Then, write a loop that prints each number and its square on a new line, like this:

The square of 12 is 144
The square of 10 is 100
...etc

**Comment by chrisbay** [comment]
Book exercise has been updated to mirror Vocareum instructions in c6baa78215309fba29d7c4212d3870b4ab4a1931
