### ISSUE TITLE
Typo: ActiveCode 5(ex_3_6)

### ISSUE THREAD

**Issue by tmaaz** [LaunchCodeEducation/thinkcspy#14]
“On Friday nights during the June, the…”
- should be either "during the month of June", or have the "the" removed.

**Comment by chrisbay** [comment]
Hi @tmaaz. I'm not finding this. Can you provide a direct link to the page in question?

**Comment by tmaaz** [comment]
Sorry for the delay, Chris. I just went through all the chapters of the book and studios that I've completed so far, page-by-page to find it... I couldn't even find this example anymore, much less the typo. When I realized that I also couldn't find the example problem we had to complete about the Olympics (which came shortly after the typo), I started to question my sanity... but now I think those two things are both in the "Hello World" book, and not the main course book. 

Sorry for the inconvenience.
