### ISSUE TITLE
Previous section tooltip includes html tags

### ISSUE THREAD

**Issue by bgschiller** [LaunchCodeEducation/thinkcspy#17]
The tooltips on buttons to go to previous/next section include html artifacts.

Visible, for example, at https://runestone.launchcode.org/runestone/static/thinkcspy/PythonTurtle/FlowofExecutionoftheforLoop.html

![](http://162.209.109.174/2016-10-27_01-21-39DQ9AV2.png)

**Comment by chrisbay** [comment]
Fixed in 347c07640814628dd1fc0e0be8fb134e746ad578

**Comment by bgschiller** [comment]
@chrisbay it looks like just that one instance was fixed. I think it's most chapter headings. Maybe it's not worth fixing now, but I'm still seeing the html in tooltips:

![](http://162.209.109.174/2016-11-09_14-32-15HFJMCU.png)

**Comment by seraries** [comment]
Happens b/w 6 and 7 in Python Turtle Chapter 4. When inline code in title. Either change titles or fix other ways.

**Comment by seraries** [comment]
Remove inline code from titles.
