### ISSUE TITLE
PythonTurtle: Exercises: #7 - TimeLimitError

### ISSUE THREAD

**Issue by tmaaz** [LaunchCodeEducation/thinkcspy#19]
The exercise is throwing a runtime error, due to how many times the turtle is spinning --
"TimeLimitError: Program exceeded run time limit. on line 5"
It appears that the book format has a 10 second time limit on runs - 
I added the line "tess.speed(5)" to expedite the process, and it worked well (while not being too fast to see the direction it was moving).

**Comment by seraries** [comment]
Turtle just spins and spins and then you get an error. The introductory sentence about this exercise does not seem to be accurate.

**Comment by JMNofziger** [comment]
Submitted a pull request with @tmaaz recommended change

**Comment by chrisbay** [comment]
Fixed by #78.

Clarification suggested by @seraries fixed by db6a0f188af9f6ac9809fb6a2671ea39a51386d0
