### ISSUE TITLE
vague wording on Chapter 3 Assignment

### ISSUE THREAD

**Issue by bgschiller** [LaunchCodeEducation/thinkcspy#20]
https://runestone.launchcode.org/runestone/static/thinkcspy/Debugging/Exercises.html#weekly-graded-assignment

Chapter 3 Assignment _implies_, but never actually says, that the temperature will always start at 40. I had a student who thought that she needed to make the program work for any starting temperature, which is a harder problem.

**Comment by chrisbay** [comment]
Fixed in 3161dd79166c936db8408d52e7528528e177b821
