### ISSUE TITLE
Section on Error Types Needs Examples

### ISSUE THREAD

**Issue by jesseilev** [LaunchCodeEducation/thinkcspy#21]
In the Debugging chapter, there is a page for each "type" of error: 
- [Syntax error](https://runestone.launchcode.org/runestone/static/thinkcspy/Debugging/Syntaxerrors.html)
- Runtime error
- Semantic error

Each page should contain an ActiveCode example that demonstrates the error in question.

**Comment by seraries** [comment]
Very good idea!

**Comment by seraries** [comment]
Fixed
