### ISSUE TITLE
Audit example and exercise code for PEP-0008 compliance

### ISSUE THREAD

**Issue by chrisbay** [LaunchCodeEducation/thinkcspy#22]
[PEP-0008](https://www.python.org/dev/peps/pep-0008/)

**Comment by seraries** [comment]
Style guide issue: introduce students to the style guide. Fix book and our code examples to match style guide.

**Comment by JMNofziger** [comment]
I'd be happy to contribute. A style guide would be great.

**Comment by seraries** [comment]
Have incorporated style guide into book. Made another issue to make naming more Pythonic throughout book.
