### ISSUE TITLE
Hardmode: Wagon Wheel Studio (DRY Principle)

### ISSUE THREAD

**Issue by wells101** [LaunchCodeEducation/thinkcspy#24]
Wagon Wheel can be implemented to do just squares as in the problem, but you can take the problem further.  In a job environment, you'll generally want to write reusable code that can handle a variety of inputs and reliably produce the desired result.  This way, you don't repeat yourself, otherwise known as the DRY Principle.

For this hard mode, can you modify Wagon Wheel to accept an additional argument specifying the desired number of sides the drawn shape is going to have?

Helpful tips:

- A regular polygon has interior angles that total to ( x - 2) * 180 degrees.
- Think about what it means to call left(x) on a turtle.

**Comment by jesseilev** [comment]
@wells101 awesome thanks.

@chrisbay FYI the idea here is like an extra credit Hacker Version of the studio.

**Comment by jesseilev** [comment]
Accidentally closed this

**Comment by seraries** [comment]
This principle is covered in other examples and exercises.
