### ISSUE TITLE
Chapter 6: boolean expression question

### ISSUE THREAD

**Issue by garrypolley** [LaunchCodeEducation/thinkcspy#25]
I think the boolean expression question is confusing.

It claims that `True` is an expression when it is also a literal. I think this will be confusing for people because it's an expression and a literal. Maybe if the text mentioned this just above, about how `bool` types are "singular" expressions.

**Comment by jesseilev** [comment]
@garrypolley thanks. Can you point to the exact question you're referring to?

**Comment by garrypolley** [comment]
It's the one on the first page I think of the chapter. 

It says to select all of the boolean expressions.  One is `True` and the other two options have a `==` in them. If you need I can find the specific spot once I get home.

**Comment by seraries** [comment]
Just take out True as an option among the answers--do it when I'm set up in text
