### ISSUE TITLE
numbered sub-sections on table of contents

### ISSUE THREAD

**Issue by bgschiller** [LaunchCodeEducation/thinkcspy#27]
A student requested that instead of bullets on [the table of contents](https://runestone.launchcode.org/runestone/static/thinkcspy/toc.html), each sub-section could be numbered. That way they can say "I'm having trouble on section 3.4" instead of having to convey the section by title alone.

![](http://162.209.109.174/2016-11-04_01-11-30JH0BDU.png)

**Comment by chrisbay** [comment]
I'll look into this, but the Table of Contents is auto-generated by the build tool that generates the book pages from RST, so we may not have control over this.

**Comment by chrisbay** [comment]
Fixed in b4387060b046df4beec35d97fb805bcc13c4e26f
