### ISSUE TITLE
Inaccurate copy in Ch 7

### ISSUE THREAD

**Issue by chrisbay** [LaunchCodeEducation/thinkcspy#33]
"2-Dimensional Iteration: Image Processing" from chapter 7

Refers to `newimg` which doesn't appear in the example code.

**Comment by seraries** [comment]
Lots of references to newimg and creating an empty image first, although program doesn't do this and doesn't seem to need to to run correctly. Fix copy is same solution consistently used of replacing pixels in original image--not in a copy!
