### ISSUE TITLE
runestone | Hello, World!

### ISSUE THREAD

**Issue by e-inquirer** [LaunchCodeEducation/thinkcspy#34]
runestone | Hello, World!: [Studios - Turtles]

> Write a program that asks the **_use_** for a size, and draws a square with sides of that length.

> Now, write a program that asks the **_use_** for a size and a number of sides, and draws a regular polygon with sides of that length.

In both sentences, the word 'use' should be replaced by 'user.'

**Comment by e-inquirer** [comment]
runestone | Hello, World!: <Mark as completed>

"Mark as completed" feature not functional for the following sections:

**2.8** - Chapter 2 practice
**3.5** - Chapter 3 practice
**4.5** - For-loop syntax revisited
**Studios** - Pi

I believe this issue arose after migrating to Runestone.

**Comment by chrisbay** [comment]
Moved these to the helloworld repo as separate issues.
