### ISSUE TITLE
Chapter 7: Exercises - Can't be marked as completed

### ISSUE THREAD

**Issue by tmaaz** [LaunchCodeEducation/thinkcspy#37]
The "Mark as Completed" button on this page is not activating when it's clicked, so students can not mark the section as being completed.

**Comment by seraries** [comment]
It worked for me as of 4/5/17. Has it been fixed? Works for some; not others. Complex to fix. Tech team working on it.

**Comment by seraries** [comment]
Part of the tech team's workflow now; not fixable by Ed team.
