### ISSUE TITLE
Clarification on hw problem

### ISSUE THREAD

**Issue by chrisbay** [LaunchCodeEducation/thinkcspy#39]
[More about Iteration](https://runestone.launchcode.org/runestone/static/thinkcspy/MoreAboutIteration/Exercises.html)

A student thought the instructions are too vague. Didn't realize that the directions applied to the entire image until she looked at the answer code.

**Comment by seraries** [comment]
This seems to be fixed. 
![image](https://cloud.githubusercontent.com/assets/20820547/24714400/00ae6a3c-19ee-11e7-95ea-57a6a1f2caef.png)
