### ISSUE TITLE
Chapter 9, exercise 10

### ISSUE THREAD

**Issue by stlou** [LaunchCodeEducation/thinkcspy#42]
Message from student:

In ch. 9 exercise 10, where the goal is to create a function called "rot13" that uses the Caesar cipher to encrypt a message, one of the test messages has an uppercase letter and the number 13 in it. The inclusion of uppercase and numerics in the message creates some obstacles if you're substituting with just the lower-case alphabet. Although there are some workarounds, like retaining the character from the message if it's not lowercase, the test case in the solution that's provided contains all lowercase--the number is spelled out. So I wasn't sure if the inclusion of uppercase and the numeric in the test message for the exercise was an oversight.

**Comment by seraries** [comment]
There is indeed a discrepancy between what the test string is for the question and for the answer. 
![screenshot 413](https://cloud.githubusercontent.com/assets/20820547/24715009/c05e1890-19ef-11e7-91bc-a52c0683de3b.png)
![screenshot 414](https://cloud.githubusercontent.com/assets/20820547/24715010/c0619b28-19ef-11e7-8a06-feae66ce02f9.png)
