### ISSUE TITLE
Chapter 10

### ISSUE THREAD

**Issue by stlou** [LaunchCodeEducation/thinkcspy#44]
Student message: 

Chapter 10, section Repetition and References, created some extra confusion for me and perhaps presentation of the concepts could be illustrated more fully. In reading through the concepts for the section it is presented as if `[list_var]*n` is the same as `list_var*n`, even though they are not.  It seems worthwhile to expand the section further and highlight that while `newlist = [origlist]*3` creates a list of three references to `origlist`; `newlist = origlist*3` creates a new object.

**Comment by seraries** [comment]
I could use some clarification on this as well. Go over with Chris--esp. the "check your understanding" part.
