### ISSUE TITLE
Crypto Sub-headers Are Numbered Crazily

### ISSUE THREAD

**Issue by jesseilev** [LaunchCodeEducation/thinkcspy#50]
It's due to that auto-numbering system that we set up. It doesn't work so well for Crypto. Very messy and confusing.

For example, https://runestone.launchcode.org/runestone/static/thinkcspy/ProblemSets/Crypto.html#b-new-feature-command-line-arguments

**Comment by chrisbay** [comment]
Fixed by b4387060b046df4beec35d97fb805bcc13c4e26f
