### ISSUE TITLE
Replace videos

### ISSUE THREAD

**Issue by chrisbay** [LaunchCodeEducation/thinkcspy#57]
Previous videos:
- [Accumulator Pattern](http://media.interactivepython.org/thinkcsVideos/accumulatorpattern.webm)
- [Function Intro](http://media.interactivepython.org/thinkcsVideos/FunctionsIntro.webm)
- [Executing Python In This Book](http://media.interactivepython.org/thinkcsVideos/activecodelens.webm)
- [The While Loop](http://media.interactivepython.org/thinkcsVideos/whileloop.webm)
- [Turtle Intro](http://media.interactivepython.org/thinkcsVideos/turtleintro.webm)
- [Modules](http://media.interactivepython.org/thinkcsVideos/modules.webm)
- [Random Module](http://media.interactivepython.org/thinkcsVideos/mathrandommodule.webm)
- [The For Loop](http://media.interactivepython.org/thinkcsVideos/for_loop.webm)
- [The Range Function](http://media.interactivepython.org/thinkcsVideos/AdvancedRange.webm)
- [Boolean Expressions](http://media.interactivepython.org/thinkcsVideos/booleanexpressions.webm)
- [Binary Selection](http://media.interactivepython.org/thinkcsVideos/binaryselection.webm)
- [Unary selection](http://media.interactivepython.org/thinkcsVideos/unaryselection.webm)
- [Input](http://media.interactivepython.org/thinkcsVideos/input.webm)
- [Precedence](http://media.interactivepython.org/thinkcsVideos/precedence.webm)
- [Associativity](http://media.interactivepython.org/thinkcsVideos/associativity.webm)
- [Updating variables](http://media.interactivepython.org/thinkcsVideos/update.webm)
- [Variables](http://media.interactivepython.org/thinkcsVideos/TypesNTypeConversion.webm)
- [Reassignment](http://media.interactivepython.org/thinkcsVideos/reassignment.webm)

**Comment by seraries** [comment]
Are these videos that use to be hyperlinked in the text? Is there a newer version of each that should be used instead, or should these just be added back in to the text? Is it beneficial if students are also getting in-class instruction/walkthroughs?
We need new videos instead, ones that add content rather than repeat it.

**Comment by seraries** [comment]
For now, just remove all videos. Later we can make new ones if desired.
