### ISSUE TITLE
Add Exceptions chapter from upstream

### ISSUE THREAD

**Issue by chrisbay** [LaunchCodeEducation/thinkcspy#58]
See: http://interactivepython.org/runestone/static/thinkcspy/index.html#

**Comment by seraries** [comment]
Maybe add this after the Debugging chapter (or merge with debugging)? Show type casting example. Add try/except to end of debugging chapter?

**Comment by seraries** [comment]
Fixed with "Merge branch addExceptions into lc_develop" on 5/1/17.
