### ISSUE TITLE
Reference to Nonexistent Variable

### ISSUE THREAD

**Issue by jesseilev** [LaunchCodeEducation/thinkcspy#62]
In this chapter, there is an active code block accompanied by an explanation, which mentions a variable called `newimg`. But the code sample does not actually have a variable called `newimg`.

http://127.0.0.1:8000/runestone/static/thinkcspy/MoreAboutIteration/2DimensionalIterationImageProcessing.html

**Comment by seraries** [comment]
Closing this issue as it is a duplicate of issue #33
