### ISSUE TITLE
TimeLimit error Ch.4 Ex. 7

### ISSUE THREAD

**Issue by chrisbay** [LaunchCodeEducation/thinkcspy#75]
Ch. 4 Ex. 7 - The code to run causes a TimeLimit error. Looks like it rotates for too long

**Comment by JMNofziger** [comment]
I believe this is the same issue referenced in ticket #19 and addressed by my pull request #78

**Comment by JMNofziger** [comment]
@chrisbay PR #78 should have fixed this issue which is also referenced in ticket #19 
Recommend that both this and issue #19 be closed.

**Comment by chrisbay** [comment]
Fixed by #78
