### ISSUE TITLE
Vocareum issue: Ch. 3 Graded Assignment

### ISSUE THREAD

**Issue by chrisbay** [LaunchCodeEducation/thinkcspy#76]
Ch.3 graded assignment doesn’t test multiple rotation - I submitted chapter 3 and got it correct, but then I realized it was actually not correct for rotation more than twice (such as 200 clicks). When I checked, the automated system that grade it didn’t test for larger number that rotate more than twice. Maybe someone should include that.

**Comment by seraries** [comment]
Fixed
