### ISSUE TITLE
Table of Contents erratically marked for completed

### ISSUE THREAD

**Issue by seraries** [LaunchCodeEducation/thinkcspy#81]
Seattle students have been pointing out that the TOC doesn't mark correctly when lessons have been completed, and that some lessons aren't able to be marked as complete. Maybe just remove this feature; it's not essential.

**Comment by JMNofziger** [comment]
I love that feature but understand it's not essential. I really enjoy the 'checklist' feel of the table of contents.

**Comment by seraries** [comment]
Check if this is still an issue or if it has been fixed.
